name: ubihrm
description: Basic app for managing leave, time off, attendance and various reports

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  camera: ^0.5.4+1
  charts_flutter: ^0.5.0
  gradient_app_bar: ^0.0.1
  font_awesome_flutter: ^8.0.1
  dio: ^1.0.13
  shared_preferences: ^0.4.3
  modal_progress_hud: ^0.1.2
  sticky_headers: ^0.1.8
  datetime_picker_formfield: ^0.4.2
  firebase_messaging: ^5.0.2
  connectivity: 0.3.2
  date_format: ^1.0.6
  flutter_slidable: ^0.4.9
  rounded_modal: ^1.0.0
  image_picker: ^0.6.1+4
  image: ^2.0.4
  #flutter_image_compress: ^0.2.2
  http: ^0.12.0+1
  path_provider: ^0.4.1
  validate: ^1.7.0
  intl: ^0.15.6
  #simple_permissions: ^0.1.9
  permission_handler: ^3.2.2
  geocoder: ^0.2.1
  json_annotation: ^0.2.3
  flutter_launcher_icons: "^0.6.1"
  barcode_scan: ^1.0.0
  url_launcher: ^4.0.1
  splashscreen: ^1.1.0
  share: ^0.5.3
  launch_review: ^1.0.1
  location: ^2.3.5
  photo_view: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/launch_logo.png"
  image_path_android: "assets/launch_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
        - assets/avatar.png
        - assets/attendance_icon.png
        - assets/leave_icon.png
        - assets/timeoff_icon.png
        - assets/reports.png
        - assets/settings.png
        - assets/visits.png
        - assets/profile.png
        - assets/img/login_logo.png
        - assets/img/logohrmbg.png
        - assets/attendance_icon1.png
        - assets/leave_icon1.png
        - assets/timeoff_icon1.png
        - assets/reports1.png
        - assets/settings1.png
        - assets/profile1.png
        - assets/reporr.png
        - assets/Hom.png
        - assets/qr.png
        - assets/cir.png
        - assets/reportt.png
        - assets/repo.ico
        - assets/approval.png
        - assets/spinner.gif
        - assets/icons/Attendance_icon.png
        - assets/icons/graph_icon.png
        - assets/icons/leave_icon.png
        - assets/icons/profile_icon.png
        - assets/icons/settings_icon.png
        - assets/icons/Timeoff_icon.png
        - assets/icons/Salary_icon.png
        - assets/icons/Expense_icon.png
        - assets/icons/Dashboard_icon.png
        - assets/icons/Flexi_icon.png
        - assets/icons/visits_icon.png






  fonts:
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf



  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
